#!/usr/bin/env python3
"""
Script to fix syntax issues in insight pages generated by the batch update script.
Main issues:
1. Single quotes in JSON-like object literals (should be double quotes or no quotes)
2. Escaped unicode characters for emojis
3. Malformed JSX content with HTML entities
"""

import os
import re

INSIGHTS_DIR = '/home/ubuntu/newco-website/client/src/pages/insights'

# Files that are already correct (manually updated)
SKIP_FILES = [
    'CorporateVentureAdvantage.tsx',
    'FromMVPToScale.tsx', 
    'HiringForBuilders.tsx',
    'CeoGuideDataModernization.tsx',
    'BuildingDataCulture.tsx',
    'DataLakeToValueStream.tsx',
    'AIAgentsTransformOperations.tsx',
    'AIInEcommerce.tsx',
    'WhyNPSIsAVanityMetric.tsx',
]

# Standard related insights to use
STANDARD_RELATED = '''[
    {
      category: "Strategy",
      categoryIcon: "📊",
      title: "The CEO's Guide to Data Modernization",
      description: "Why 70% of transformations fail and how to be in the 30% that succeed.",
      readTime: "5 min read",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80",
      link: "/insights/ceo-guide-data-modernization"
    },
    {
      category: "Culture",
      categoryIcon: "🎬",
      title: "Building a Data-First Culture",
      description: "NexDyne's Chief Data Officer discusses the human side of digital change.",
      readTime: "12 min watch",
      image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80",
      link: "/insights/building-data-culture"
    },
    {
      category: "Article",
      categoryIcon: "📄",
      title: "The Corporate Venture Advantage",
      description: "Why established assets combined with startup speed create an unfair market advantage.",
      readTime: "6 min read",
      image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80",
      link: "/insights/corporate-venture-advantage"
    }
  ]'''

def fix_file(filepath):
    """Fix syntax issues in a single file."""
    filename = os.path.basename(filepath)
    
    if filename in SKIP_FILES:
        print(f"Skipping {filename} (already correct)")
        return False
    
    with open(filepath, 'r') as f:
        content = f.read()
    
    # Skip if it doesn't use InsightArticleLayout
    if 'InsightArticleLayout' not in content:
        print(f"Skipping {filename} (doesn't use InsightArticleLayout)")
        return False
    
    original_content = content
    
    # Fix the relatedInsights array - replace the malformed one with standard
    # Match the const relatedInsights = [...]; pattern
    pattern = r"const relatedInsights = \[[\s\S]*?\];"
    if re.search(pattern, content):
        content = re.sub(pattern, f"const relatedInsights = {STANDARD_RELATED};", content)
    
    # Fix HTML entities that shouldn't be there
    content = content.replace('&#123;', '{')
    content = content.replace('&#125;', '}')
    
    # Fix any remaining issues with JSX content
    # Remove empty className attributes
    content = re.sub(r'\s+className=""', '', content)
    content = re.sub(r'\s+class=""', '', content)
    
    # Fix unclosed tags in article content - find and remove problematic patterns
    # Look for orphaned closing tags
    content = re.sub(r'</div>\s*\n\s*&#123;', '\n      {', content)
    
    if content != original_content:
        with open(filepath, 'w') as f:
            f.write(content)
        print(f"Fixed {filename}")
        return True
    else:
        print(f"No changes needed for {filename}")
        return False

def main():
    fixed = 0
    skipped = 0
    
    for filename in os.listdir(INSIGHTS_DIR):
        if not filename.endswith('.tsx'):
            continue
        
        filepath = os.path.join(INSIGHTS_DIR, filename)
        if fix_file(filepath):
            fixed += 1
        else:
            skipped += 1
    
    print(f"\nDone! Fixed {fixed} files, skipped {skipped} files.")

if __name__ == '__main__':
    main()
